http:
  middlewares:
    pgadmin-headers:
      headers:
        customRequestHeaders:
          X-Scheme: https
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentSecurityPolicy: "default-src 'self' 'unsafe-inline' 'unsafe-eval'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;"
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true

    pgadmin-rate:
      rateLimit:
        average: 100
        burst: 50

    secure-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
    
    docs-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        sslRedirect: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
        customResponseHeaders:
          X-Robots-Tag: "noindex, nofollow, nosnippet, noarchive, notranslate, noimageindex"
          Server: ""

    docs-rate:
      rateLimit:
        average: 100
        burst: 50
        
        
        
