api:
  dashboard: true
  insecure: false

log:
  level: DEBUG

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls: {}

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: frontend
  file:
    directory: /etc/traefik
    watch: true

global:
  checkNewVersion: false
  sendAnonymousUsage: false

tls:
  certificates:
    - certFile: /certs/localhost.crt
      keyFile: /certs/localhost.key