api:
  dashboard: true

log:
  level: INFO

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true

global:
  checkNewVersion: false
  sendAnonymousUsage: false