http:
  middlewares:
    secured:
      chain:
        middlewares:
          - secure-headers
          - rate-limit

  secure-headers:
    headers:
      sslRedirect: true
      forceSTSHeader: true
      stsIncludeSubdomains: true
      stsPreload: true
      stsSeconds: 315360000
      customFrameOptionsValue: "SAMEORIGIN"
      contentTypeNosniff: true
      browserXssFilter: true
      referrerPolicy: "strict-origin-when-cross-origin"
      permissionPolicy: "geolocation=(), midi=(), sync-xhr=(), microphone=(), camera=(), magnetometer=(), gyroscope=(), fullscreen=(self), payment=()"
    
  rate-limit:
    rateLimite:
      average: 100
      burst: 50