site_name: Documentation Stack Dev B1 Pro
site_description: Documentation de la stack de développement optimisée pour B1 Pro
site_author: Votre Nom

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mode clair

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - meta
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - minify:
      minify_html: true

nav:
  - Accueil: index.md
  - Guide de Démarrage:
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - Services:
    - Bases de données:
      - MariaDB: services/databases/mariadb.md
      - Redis: services/databases/redis.md
      - Adminer: services/databases/adminer.md
    - Monitoring:
      - Portainer: services/monitoring/portainer.md
      - Netdata: services/monitoring/netdata.md
    - Proxy:
      - Traefik: services/proxy/traefik.md
  - Sécurité:
    - Accès à Distance: security/remote-access.md
    - Mesures de Sécurité: security/security-measures.md
  - Administration:
    - Gestion: admin/managment.md
    - Maintenance: admin/maintenance.md
  - Développement:
    - Bonnes Pratiques: development/best-practices.md
    - Performance: development/performance.md
  - Troubleshooting:
    - Problèmes Courants: troubleshooting/common-issues.md
    - Performances: troubleshooting/performance.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/votre-username/stack-dev
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/votre-username/stack-dev

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2024 Votre Nom